### ISSUE TITLE
omv6 type context menu button does not get disabled with enabledConstraints

### ISSUE THREAD

**Issue by subzero79** [openmediavault/openmediavault#1015]
**Is your feature request related to a problem? Please describe.**
Trying to create a context a menu for porting the luks encryption plugin. We have two context buttons that expand so i know we have more space now but i want to know if is posible to implement or it needs to be declared in another way

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/7058119/115956741-e0ecba80-a541-11eb-9628-b03486d2487a.png)

above omv5, now with omv6 using this solution:

```yaml
      - type: menu
        icon: "mdi:key"
        tooltip: _("Manage Keys")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        actions:
          - type: iconButton
            # tooltip: _("Add")
            icon: "mdi:plus"
            text: _("Add")
            execute:
              type: url
              url: "/storage/encryption/addkey"
```

![image](https://user-images.githubusercontent.com/7058119/115956782-2d37fa80-a542-11eb-867a-c3daa18fa58b.png)

Menu is enabled but no device selected

**Describe alternatives you've considered**

**Additional context**

Is it possible to auto generate the docs front end plugin development? 

Also there is not hot reload to work on this, so i am editing directly the yaml files over the installed path. as a suggestion there should be an aditional path like /usr/share/openmediavault/workbench-dev to work over the files while in development so you don't get confused with existing files or naturally installed plugins. Unless there is another workflow I am not aware

![image](https://user-images.githubusercontent.com/7058119/115956921-e696d000-a542-11eb-9bc1-443eea70ea88.png)
