### ISSUE TITLE
Adjustment of Dashboard Widgets

### ISSUE THREAD

**Issue by epicfail83** [openmediavault/openmediavault#1208]
It would be nice if you could add the possibility to change the size and position of the widgets on the Dashboard. 

Thx in advance

**Comment by votdev** [comment]
I've evaluated many libraries that support resizable widgets for OMV and other project i'm working in my job, we always returned to fixed sized widgets.

**Comment by mi-hol** [comment]
could size of "network widget" be adjusted so IPs are readable?

**Comment by votdev** [comment]
> could size of "network widget" be adjusted so IPs are readable?

No, the whole datatable automatically resizes according to the available space. A datatable is not really a good idea in a dashboard widget, so maybe writing an alternative widget that uses a different approach would be better. But as often told, OMV is a OSS project, everyone can contribute. I do not need such a widget, so i will not invest any time of my spare time for that.

**Comment by ryecoaaron** [comment]
Here is the framework for creating a very simple plugin that just adds a widget.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-cputemp
Here are the widgets provided by OMV itself - https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/openmediavault/workbench/dashboard.d

**Comment by mi-hol** [comment]
> could size of "network widget" be adjusted so IPs are readable?

Thanks for the link ryecoaaron.
What I referred to as "network widget" is actually the OMV provided  network_interfaces.yaml

` - name: _("Address")
      prop: address
      flexGrow: 1
      sortable: true
      cellTemplateName: template
      cellTemplateConfig: 'IPv4: {{ address | default("-", true) }}<br>IPv6: {{ address6 | default("-", true) }}'`

Now because "the whole datatable automatically resizes according to the available space."
and "there is no possibility to select position of the widgets on the Dashboard."

we have a catch22 situation for users.

I'm neither familiar with defining widgets nor changing them yet. 
The [documentation for dashboard](https://openmediavault.readthedocs.io/en/latest/development/plugins.html?highlight=widget#overview) doesn't provide a reference for this topic (like framework used, reference docs) yet.
So I' m stuck to solve the issue with OSS approach, or did I miss available information on "how to customize widgets"?

**Comment by votdev** [comment]
> So I' m stuck to solve the issue with OSS approach

the OSS approach is normally: Use the source Luke.

**Comment by votdev** [comment]
> could size of "network widget" be adjusted so IPs are readable?

I've improved the datatable that way that custom templated columns will show a tooltip. This should help to read the content of a cell if it is not completely visible.

![Bildschirmfoto von 2022-02-11 13-57-22](https://user-images.githubusercontent.com/1897962/153595707-e51f270f-805d-497f-9c69-78f8f8c296e3.png)

**Comment by votdev** [comment]
> > he OSS approach is normally: Use the source Luke.
> 
> I found it, but it makes no sense, without some form of documentation, explaining the meaning of words used :(

It is not my job to do everything... You want a documentation, contribute it. THAT IS OSS WORKS.

**Comment by mi-hol** [comment]
without a helping hand offered, this "chicken and egg" issue will remain forever

**Comment by votdev** [comment]
> without a helping hand offered, this "chicken and egg" issue will remain forever

It is not my job, i'm not interesting in writing docs, dot.

**Comment by ryecoaaron** [comment]
It is not the responsibility of the OMV docs to teach programming languages.  If you are a programmer, you should be able to look at the code and figure things out.  I have.

**Comment by mi-hol** [comment]
> It is not my job, i'm not interesting in writing docs

this is not what I mean by "helping hand". A "helping hand" would provide a pointer to the source file handling the "translation of yaml definition into actual behaviour".

**Comment by ryecoaaron** [comment]
There isn't one file.  It is an entire framework.  You should be able to get what you need from the yaml file.  If not, you would need to be proficient in angular.

**Comment by mi-hol** [comment]
> If not, you would need to be proficient in angular.

I've never worked with Angular. So my attempt to help seems to end here

**Comment by mi-hol** [comment]
[The Angular tutorial ](https://www.tutorialspoint.com/angular_material/angular_material_quick_guide.htm) I found has no search hits for "FlexGrow" used in above yaml either :(

**Comment by ryecoaaron** [comment]
You are still trying to change the behavior of the widgets instead of looking at just coming up with a different widget.  I don't know angular either yet I still can write widgets.  That is why I linked to widget code.

**Comment by mi-hol** [comment]
I'm confused, the existing widget contains everything desired, with the only expectation that its size is too small.
Why would I create a new widget, when only a (hopefully minor) fix of an "attribute related to size"  is required?

**Comment by ryecoaaron** [comment]
The new widget was just to test changes to the current widget.  The current network widget has too much info for the size allowed.  I highly doubt netmask and mtu (probably even gateway) need to be in the current widget.  You only have to look at the yaml to figure out to remove those and submit a pull request.

**Comment by mi-hol** [comment]
Thanks for the "helping hand". 
Actually I'd believe attributes like "minHeight" /   "minWidth" would fix the issue, but I found only the opposite i.e.  'maxHeight: "150px"'  and 'maxWidth: "150px"' in cpu.yaml
What is your view?

To understand the concepts used, would perhaps[ this tutorial ](https://www.smashingmagazine.com/2020/07/responsive-dashboard-angular-material-ng2-charts-schematics/) apply (at least partially)?

**Comment by ryecoaaron** [comment]
I fail to see how maxHeight for a chart applies to a datatable.  And regardless of how you set any heights or widths, there is still too much info the network widget.

I didn't look at your link but I didn't use it to create the cpu temp widget.  The problem you are trying to fix is not code but user interface design.

**Comment by mi-hol** [comment]
I started to reduce the fields in existing network_interfaces.yaml.
Have the following issues though:

1. after editing & replacing the file (see below), how to "activate" the change even after a reboot the old configuration was used?
2. re "maxHeight for a chart applies to a datatable" how to find out which attributes are available for a datatable?
2. even with enough free space on display area, the original yaml doesn't expand (see below)

Any hints?

new code in network_interfaces.yaml
```
version: "1.0"
type: dashboard-widget
data:
  id: 85bc79a2-f7f5-11e4-a5ad-0002b3a176b4
  title: _("Network Interfaces")
  type: datatable
  permissions:
    role:
    - admin
  datatable:
    columns:
    - name: _("Device")
      prop: devicename
      flexGrow: 1
      sortable: true
    - name: _("IPv4 Address")
      prop: address
      flexGrow: 1
      sortable: true
      cellTemplateName: template
      cellTemplateConfig: 'IPv4: {{ address | default("-", true) }}'
    - name: _("IPv6 Address")
      prop: address
      flexGrow: 1
      sortable: true
      cellTemplateName: template
      cellTemplateConfig: 'IPv6: {{ address6 | default("-", true) }}'
    - name: _("MAC")
      prop: ether
      flexGrow: 1
      sortable: true
      hidden: true
    - name: _("Speed")
      prop: speed
      flexGrow: 1
      sortable: true
      hidden: true
      cellTemplateName: template
      cellTemplateConfig: '{{ speed | replace("-1", "") | notavailable("-") }}'
    - name: _("Link")
      prop: link
      flexGrow: 1
      sortable: true
      cellTemplateName: checkIcon
    store:
      proxy:
        service: Network
        get:
          method: enumerateDevicesList
          params:
            start: 0
            limit: -1
    sorters:
    - dir: asc
      prop: devicefile

```
![image](https://user-images.githubusercontent.com/22799428/153642351-5e84c72e-1130-4bbe-a5b3-5abbb09bca6a.png)
