### ISSUE TITLE
Adding hidden wireless networks

### ISSUE THREAD

**Issue by AntonGepting** [openmediavault/openmediavault#1502]
Hello,

first of all thanks to all contributors for developing and supporting this project!

I have some feature suggestion, I have been tried to find an existing issue - nothing was found, not sure if it was already mentioned somewhere else, if so - I’m sorry, please close this issue.

Most AP's (if not all) have an option to hide SSID (in some cases it can be useful, to not overfill the list of the wireless networks of regular users with some service networks).

Configuration via web interface of the OMV does not allow to add such a hidden network, as a result it can only connect to visible wireless networks (no connection if network was hidden). 

It will be great to add an optional checkbox "hidden" in create network interface dialogue. As I can see it will have no big impact on code base (may be I'm wrong). 

Thank you in advance!

configuration via `/etc/netplan/...wlan0.yaml`
```
...
network:
    ...
    wifis:
        wlan0:
            dhcp4: true
            access-points:
                "MySSID":
                    hidden: true
                    password: "MyPSK"
...
```

configuration via `etc/network/interfaces`
```
...
auto wlan0
iface wlan0 inet dhcp
   wpa-ssid MySSID
   wpa-psk MyPSK
   wpa-scan-ssid 1
...
```

configuration via `/etc/wpa_supplicant/wpa_supplicant.conf`
```
...
network={
       ssid="MySSID"
       psk="MyPSK"
       scan_ssid=1
}
...
```
