### ISSUE TITLE
I need to turn off temporary IPV6 addresses

### ISSUE THREAD

**Issue by AxIauk** [openmediavault/openmediavault#1598]
**Is your feature request related to a problem? Please describe.**
OMV defaults to a temporary IPV6 address. I need an interface to turn it off.

**Describe the solution you'd like**
It is hoped that the network interface will add the option to turn off temporary ipv6

**Describe alternatives you've considered**
Currently I close it manually
ssh
nano /etc/netplan/20-openmediavault-enp2s0f0.yaml
ipv6-privacy: false
netplan apply

**Comment by votdev** [comment]
I don't think such an option is requred in general, so i will not add an additional option to the network interface pages.

Even there is the option to customize the OMV configuration

**Comment by geniusjoe** [comment]
> > Also since there is even already the possibility to customize the OMV configuration. Simply create a new SaltState `/srv/salt/omv/deploy/systemd-networkd/netplan/99disableipv6.sls` which replaces `ipv6-privacy: true`.
> > Check out:
> > 
> > * https://docs.openmediavault.org/en/stable/various/advset.html#the-saltstack-states
> > * https://docs.saltproject.io/en/latest/ref/states/all/salt.states.file.html#salt.states.file.replace
> 
> nano /srv/salt/omv/deploy/systemd-networkd/netplan/99disableipv6.sls customize_netplan: file.replace: - name: "/etc/netplan/20-openmediavault-enp2s0f0.yaml" - pattern: 'ipv6-privacy: true' - repl: 'ipv6-privacy: false'
> 
> Perfect, tks [votdev]

This configuration works for me. However, as a reminder, different hardware has different NICs, so you need to replace the network interface with your own. For me, my netplan file path is `20-openmediavault-eno1.yaml`.

Another thing to note: my OMV6 version is Version: 6.5.0-3. I'm not sure if it's an environment-specific issue on my end, but after configuring IPv6, there is no default IPv6 gateway, which causes pings to external destinations to fail. If you encounter a similar problem, you can consider adding routes in netplan:
```YAML
network:
  ethernets:
    eno1:
      accept-ra: true
      ipv6-privacy: false
      dhcp6: no # slaac mode
      routes:
        - to: 0.0.0.0/0
          via: <gateway ip>
        - to: "::/0"
          via: "fe80::<gateway eui64>"
```
