### ISSUE TITLE
Add option to select the WIFI band

### ISSUE THREAD

**Issue by myrck** [openmediavault/openmediavault#1875]
**Is your feature request related to a problem? Please describe.**
In my environment, both WIFI networks (2.4GHz and 5Ghz) share the same name. However, only the 2.5Ghz network is used by default.

**Describe the solution you'd like**
An option to add the band in the WIFI settings via a selection box:
**auto**: as before, do not force a band.
**2.4GHz**: Set `band: 2.4GHz` in the netplan configuration
**5GHz**: Set `band: 5GHz` in the netplan configuration

**Describe alternatives you've considered**
I have set it manually in `/etc/netplan/xxx.yml`, but it will be overwritten again after a deploy. 

**Additional context**
https://manpages.ubuntu.com/manpages/bionic/man5/netplan.5.html

**Comment by votdev** [comment]
Can you explain what you have modified/added.

BTW, you can create a separate file with your settings. Netplan will merge them automatically.

**Comment by myrck** [comment]
```
network:
  wifis:
    wlxdc15c898ec07:
      accept-ra: true
      dhcp4: yes
      dhcp4-overrides:
        use-dns: true
        use-domains: true
      dhcp6: yes
      dhcp6-overrides:
        use-dns: true
        use-domains: true
      access-points:
        "NAME":
          auth:
            key-management: psk
            password: "PASSWORD"
          hidden: false
          band: 5GHz <---- This Line
```

To clarify, I can create a separate file with this content:
```
network:
  wifis:
    wlxdc15c898ec07:
      access-points:
        "NAME":
          band: 5GHz
```
