### ISSUE TITLE
Make 4 devices fit in the grid

### ISSUE THREAD

**Issue by theking2** [openmediavault/openmediavault#1894]
**Is your feature request related to a problem? Please describe.**
the devices sind 

**Describe the solution you'd like**
4 device is kind of standard? (three is not) why not keep them in one line?

This style:

```css
.widget-content[_ngcontent-lte-c137] {
    padding: 0 1rem 1rem;
    grid-template-columns: repeat(auto-fit, minmax(9ch, 1fr));
}
```

Rationaly `/dev/sd$` is characters wide. Using 9ch gives enough space to having four items sit on one line. 

**Describe alternatives you've considered**
Tried custom css by Denis plugin didn´t work.

**Additional context**
![image](https://github.com/user-attachments/assets/b7beb38b-762e-4765-a6d3-6a051b4fa33d)
