### ISSUE TITLE
Tokens not being replaced in RPC requests when using formPage + datatable + formDialogConfig

### ISSUE THREAD

**Issue by DerDreschner** [openmediavault/openmediavault#1918]
**Describe the bug**

I'm currently developing a new plugin for OpenMediaVault. During development, I experienced a possible bug regarding `formDialog` elements, which leads to tokens not being processed when doing RPC requests.

I want to create a `formPage` with a `datatable` inside. This data table uses a `formDialogConfig` for the add button. For the fields in the form dialog, I have to make parameterized RPC calls using objects from the `PageContext` variables (`_routeQueryParams` and `_routeParams` to be precise). But no matter what I do, the tokens are not being replaced. The raw value is being pushed to the RPC service without any change.

This is unexpected, as the token replacement for the `formDialog` works when using a `datatablePage` instead. But this isn't a possible workaround in my case.

**To Reproduce**

1. Create a new page with the following component:

```yaml
version: "1.0"
type: component
data:
  name: omv-services-bugreport-form-page
  type: formPage
  config:
    request:
        service: ShareMgmt
        get:
          method: enumerateSharedFolders
    fields:
      - type: datatable
        label: _("Bugreport")
        columns:
          - name: _("Column 1")
            prop: column1
            flexGrow: 1
            cellTemplateName: copyToClipboard
          - name: _("Column 2")
            prop: column2
            flexGrow: 1
            cellTemplateName: copyToClipboard
        actions:
          - template: add
            formDialogConfig:
              title: _("Add new lorem ipsum")
              fields:
                - type: select
                  name: bugField
                  label: _("This is a bug")
                  store:
                    proxy:
                      service: bugService
                      get:
                        method: getBugreportField
                        params:
                          value: "{{ _routeQueryParams.exampleValue }}"
```

2. Open the new page with the queryParameter `?exampleValue=test` added to the URI.
3. Try to add a new element to the data table.
4. Check the request against the RPC service. It should look like this:

```json
{
	"method": "getBugreportField",
	"params": {
		"value": "{{ _routeQueryParams.exampleValue }}"
	},
	"service": "bugService"
}
```

**Expected behavior**

The token of the parameter should have been replaced with the "test" value from the `exampleValue` query parameter. The request body would look like this then:

```json
{
	"method": "getBugreportField",
	"params": {
		"value": "test"
	},
	"service": "bugService"
}
```

**openmediavault Server**

- OS version: `Linux server 6.12.9+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.9-1~bpo12+1 (2025-01-19) x86_64 GNU/Linux`
- openmediavault version: 7.6.0-1

**Client**

- Device: Lenovo ThinkPad T15g Gen2
- OS: Linux Mint 22.1
- Browser: Mozilla Firefox
- Version: 134.0.2 (64-bit)

**Comment by votdev** [comment]
This is not a bug. This feature is still not implemented. Strings are not replaced in that depth; only on the form page fields level.

**Comment by votdev** [comment]
Please report back if it works for you.

**Comment by DerDreschner** [comment]
Hey @votdev, thanks for your very quick solution! Unfortunately, I found another edge case that isn't covered yet. When I try to add modifiers to the `bugField` selection in the form dialog, the values are not replaced as the `pageContext` is empty there.

I don't want to steal anymore precious time from you, that's why I did a rewrite to the pageContext handling myself and moved it to a global service. That way, I didn't found any case where the pageContext isn't empty.

I open the pull request shortly as well as the signed OCA. Hope that's okay and satisfy your standards.

**Comment by DerDreschner** [comment]
Just for reference, this is an example of the case that didn't worked without my change as the pageContext was empty when evaluating the modifiers in my debugging. The original case from above did work after your change, just to make that clear. 

```yaml
version: "1.0"
type: component
data:
  name: omv-services-bugreport-form-page
  type: formPage
  config:
    request:
      service: ShareMgmt
      get:
        method: enumerateSharedFolders
        params:
          value: "{{ _routeQueryParams.exampleValue }}"
    fields:
      - type: datatable
        label: _("Bugreport")
        columns:
          - name: _("Column 1")
            prop: column1
            flexGrow: 1
            cellTemplateName: copyToClipboard
          - name: _("Column 2")
            prop: column2
            flexGrow: 1
            cellTemplateName: copyToClipboard
        actions:
          - template: add
            formDialogConfig:
              title: _("Add new lorem ipsum")
              fields:
                - type: select
                  name: bugField
                  label: _("This is a bug")
                  store:
                    proxy:
                      service: bugService
                      get:
                        method: getBugreportField
                        params:
                          value: "{{ _routeQueryParams.exampleValue }}"
                  modifiers:
                    - type: visible
                      constraint:
                        operator: truthy
                        arg0:
                          prop: "{{ _routeQueryParams.exampleValue }}"
```
