### ISSUE TITLE
Bug: Validator doesn't run on page initialization

### ISSUE THREAD

**Issue by DerDreschner** [openmediavault/openmediavault#1920]
**Describe the bug**

The validator for a form isn't called on page initialization. In my case (the `openmediavault-kvm` plugin, formDialog `Create consoles`), the form has `required` fields which are pre-filled with a default value. This bug leads to the problem, that the form can not be submitted until doing any value change (button is disabled), although this isn't necessary as the default values makes the form valid by itself.

**To Reproduce**

1. Create a new page with the following component:

```yaml
version: "1.0"
type: component
data:
  name: omv-services-bugreport-form-page
  type: formPage
  config:
    fields:
      - type: textInput
        name: type
        label: _("value1")
        value: "lorem ipsum"
        validators:
          required: true
    buttons:
      - template: submit
        execute:
          type: url
          url: /
```

2. Open the new page and try to click the "Save" button.
3. The button is disabled.

**Expected behavior**

I'm able to submit the form when it's valid by default.

**Screenshots**

![Image](https://github.com/user-attachments/assets/b4a7f7c7-5be5-4eb7-9f9c-45bfa988fd48)

**openmediavault Server:**

- OS version: `Linux server 6.12.9+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.9-1~bpo12+1 (2025-01-19) x86_64 GNU/Linux`
- openmediavault version: 7.6.0-1

**Client:**

- Device: Lenovo ThinkPad T15g Gen2
- OS: Linux Mint 22.1
- Browser: Mozilla Firefox
- Version: 134.0.2 (64-bit)

**Additional context**

The bug isn't that important for myself, but I wanted to report it anyway as it annoys me approximately once a year. 😄 So, no hurry.

**Comment by votdev** [comment]
You've set the `editing` property in the route configuration, which is incorrect in that case. This property only needs to be set when a RPC needs to be executed to load the form values from the backend.

**Example**
```
version: "1.0"
type: route
data:
  url: "/services/wetty"
  title: _("WeTTY")
  notificationTitle: _("Updated WeTTY settings.")
  component: omv-services-wetty-form-page
  editing: true    <========
```
