### ISSUE TITLE
Allow configuration of additional entrypoints in k8s plugin

### ISSUE THREAD

**Issue by YurNaybor** [openmediavault/openmediavault#1940]
**Is your feature request related to a problem? Please describe.**
I would like to run Gitea in K8s on OMV and make it accessible via SSH. Having the provided Traefik handle the incoming traffic, I would need a dedicated entrypoint for the TCP based traffic. Now, on OMV Traefik is configured via HelmChartConfig in /var/lib/rancher/k3s/server/manifests/openmediavault-traefik.yaml, which is managed by OMV. Changes to the file would probably be overwritten by OMV. I see no other way to extend the Traefik configuration.

**Describe the solution you'd like**
In the general settings of the OMV K8s plugin, a new section could be added to allow for adding additional entrypoints, which are then rendered in openmediavault-traefik.yaml. This would allow to add non-http services to be handled by traefik.

**Describe alternatives you've considered**
Exposing the service via NodePort, but I was unable to reach the opened port from hosts other than the OMV system. I may have to dig into firewall rules for this, but I thought that configuration of entrypoints may be a feature that is interesting for others, too,

**Additional context**
-

**Comment by votdev** [comment]
Entrypoints are configured and applied during installation of the Traefik Helm chart during the installation of K3s. This is only done once. I'm not sure how this could be implemented in a user-friendly way.

**Comment by votdev** [comment]
Maybe this can help in this case: https://qdnqn.com/how-to-configure-traefik-on-k3s/

**Comment by votdev** [comment]
References:
- https://doc.traefik.io/traefik/getting-started/configuration-overview/?ref=qdnqn.com#the-static-configuration
- https://doc.traefik.io/traefik/routing/entrypoints/

**Comment by votdev** [comment]
I'm not sure how to implement such a complex configuration in a simple and user-friendly way. Simply providing a text field for YAML code is not exactly OMV's approach.

**Comment by YurNaybor** [comment]
Given the folling mockup, which I would like to reach:

```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: openmediavault
spec:
  valuesContent: |-
    ports:
      # Hard coded entrypoints / ports
      web:
        exposedPort: 80
      websecure:
        exposedPort: 443
      dashboard:
        port: 4443
        protocol: TCP
        expose:
          default: true
        exposedPort: 4443
        tls:
          enabled: true
      # Additional entrypoints / ports configured via OMV
      gitea-ssh:
        exposedPort: 2222
      anotherone:
        exposedPort: 1234
```

In OMV, I would only need to be able to configure a list of ports with their names. Personally, I don't need any other configuration for entrypoints. It would even be fine for me if entrypoint name matches port name, so that there's not even need to configured it as a list of key value entries in OMV. It could then even be implemented using environment variables instead of UI, like documented here: https://docs.openmediavault.org/en/stable/various/advset.html, e.g. having a variable that contains a list of entrypoints, like `OMV_K8S_ADDITIONAL_ENTRYPOINTS=gitea-ssh:2222,anotherone:1234` or  `OMV_K8S_ADDITIONAL_ENTRYPOINTS=2222,1234`
