### ISSUE TITLE
Salt ID must be uniques?

### ISSUE THREAD

**Issue by subzero79** [openmediavault/openmediavault#340]
Just starting to test from the iso. Avahi services for NFS are generated one per share, enabling more than one share doesn't report error in the webui in NFS setup, but as soon as any other service is enabled like FTP or Samba salt complains.

![image](https://user-images.githubusercontent.com/7058119/56449593-ee717780-635e-11e9-9762-e90c629db4f2.png)

Seems like ID's for salt have to be unique as iterating over the array of shares.

```
oot@openmediavault:/srv/salt/omv/deploy/avahi/services# omv-salt deploy run avahi
/usr/lib/python3/dist-packages/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
debian:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.avahi.services.nfs' failed: while constructing a mapping
  in "<unicode string>", line 25, column 1:
    remove_avahi_service_nfs:
    ^
found conflicting ID 'configure_avahi_service_nfs'
  in "<unicode string>", line 59, column 1:
    configure_avahi_service_nfs:
    ^
```

Changed this code 

https://github.com/openmediavault/openmediavault/blob/a8270541e350f21460b826a8a20bbcf2c3f3d7c3/deb/openmediavault/srv/salt/omv/deploy/avahi/services/nfs.sls#L42-L46

To this for passing the deploy

```
configure_avahi_service_nfs_{{ sharedfolder.name }}:
  file.managed:
    - name: "/etc/avahi/services/nfs-{{ sharedfolder.name }}.service"
    - source:
      - salt://{{ slspath }}/files/template.j2
    - template: jinja
```

BTW how can we see (debug) the rendering for this new configuration way in OMV? before i use `set -x` in bash, is there something we can check to see how the jinja2 templates evaluate
