### ISSUE TITLE
SMB enabling: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'timemachine'

### ISSUE THREAD

**Issue by remidebette** [openmediavault/openmediavault#667]
### Description of issue/question
Hi, I have just reinstalled OMV to 5.3.9-1 from an existing OMV 4.
I had 4 SMB shares that are still properly configured and that I want to enable again.

### Steps to reproduce issue

After enabling, saving and applying. I get the following error:
```yaml
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run avahi 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(exes, collections.Iterable):
raspberrypi:
----------
          ID: mask_avahi_service
    Function: service.masked
        Name: avahi-daemon
      Result: True
     Comment: Service avahi-daemon was masked
     Started: 21:20:45.692885
    Duration: 1853.109 ms
     Changes:
              ----------
              masked:
                  ----------
                  new:
                      True
                  old:
                      False
----------
          ID: stop_avahi_socket
    Function: service.dead
        Name: avahi-daemon.socket
      Result: True
     Comment: Service avahi-daemon.socket has been disabled, and is dead
     Started: 21:20:47.547428
    Duration: 2402.957 ms
     Changes:
              ----------
              avahi-daemon.socket:
                  True
----------
          ID: stop_avahi_service
    Function: service.dead
        Name: avahi-daemon.service
      Result: True
     Comment: Service avahi-daemon.service is already disabled, and is dead
     Started: 21:20:49.951808
    Duration: 648.433 ms
     Changes:
              ----------
              avahi-daemon.service:
                  False
----------
          ID: configure_default_avahi_daemon
    Function: file.managed
        Name: /etc/default/avahi-daemon
      Result: True
     Comment: File /etc/default/avahi-daemon is in the correct state
     Started: 21:20:50.615840
    Duration: 303.976 ms
     Changes:
----------
          ID: configure_avahi_daemon_conf
    Function: file.managed
        Name: /etc/avahi/avahi-daemon.conf
      Result: True
     Comment: File /etc/avahi/avahi-daemon.conf is in the correct state
     Started: 21:20:50.920829
    Duration: 72.476 ms
     Changes:
----------
          ID: remove_avahi_service_ftp
    Function: file.absent
        Name: /etc/avahi/services/ftp.service
      Result: True
     Comment: File /etc/avahi/services/ftp.service is not present
     Started: 21:20:50.994308
    Duration: 2.795 ms
     Changes:
----------
          ID: remove_avahi_service_nfs
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 21:20:51.001750
    Duration: 7.141 ms
     Changes:
              ----------
              file.find:
----------
          ID: remove_avahi_service_rsync
    Function: file.absent
        Name: /etc/avahi/services/rsync.service
      Result: True
     Comment: File /etc/avahi/services/rsync.service is not present
     Started: 21:20:51.009878
    Duration: 2.638 ms
     Changes:
----------
          ID: configure_avahi_service_smb
    Function: file.managed
        Name: /etc/avahi/services/smb.service
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'timemachine'
     Started: 21:20:51.013373
    Duration: 138.324 ms
     Changes:
----------
          ID: configure_avahi_service_ssh
    Function: file.managed
        Name: /etc/avahi/services/ssh.service
      Result: True
     Comment: File /etc/avahi/services/ssh.service is in the correct state
     Started: 21:20:51.152735
    Duration: 53.696 ms
     Changes:
----------
          ID: configure_avahi_service_webadmin
    Function: file.managed
        Name: /etc/avahi/services/website.service
      Result: True
     Comment: File /etc/avahi/services/website.service is in the correct state
     Started: 21:20:51.207463
    Duration: 64.449 ms
     Changes:
----------
          ID: unmask_avahi_service
    Function: service.unmasked
        Name: avahi-daemon
      Result: True
     Comment: Service avahi-daemon was unmasked
     Started: 21:20:51.272962
    Duration: 1887.25 ms
     Changes:
              ----------
              masked:
                  ----------
                  new:
                      False
                  old:
                      True
----------
          ID: start_avahi_socket
    Function: service.running
        Name: avahi-daemon.socket
      Result: True
     Comment: Service avahi-daemon.socket has been enabled, and is running
     Started: 21:20:53.161064
    Duration: 2598.098 ms
     Changes:
              ----------
              avahi-daemon.socket:
                  True
----------
          ID: start_avahi_service
    Function: service.running
        Name: avahi-daemon.service
      Result: True
     Comment: Service avahi-daemon.service is already enabled, and is running
     Started: 21:20:55.760469
    Duration: 512.286 ms
     Changes:
              ----------
              avahi-daemon.service:
                  True

Summary for raspberrypi
-------------
Succeeded: 13 (changed=7)
Failed:     1
-------------
Total states run:     14
Total run time:   10.548 s in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatuskM...', '/tmp/bgoutputlC...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

### Versions report
5.3.9-1
