### ISSUE TITLE
Network MTU value doesn't get applied

### ISSUE THREAD

**Issue by getSurreal** [openmediavault/openmediavault#689]
Per the documentation for netplan you must match the nic by MAC address for the MTU value to be applied.  https://netplan.io/reference

### Steps to reproduce issue
Set the MTU to 9000 from the admin panel
Run ifconfig from the termianl and the MTU is still 1500

### Resolution
Edit /etc/netplan/20-openmediavault-{your-nic}.yaml and add "match: macaddress"

Before:
```
network:
  ethernets:
    enp2s0:
      addresses:
      - 192.168.0.12/24
      gateway4: 192.168.0.1
      dhcp4: false
      dhcp6: false
      link-local: []
      nameservers:
        addresses:
        - 192.168.0.2
      mtu: 9000
```

After:

```
network:
  ethernets:
    enp2s0:
      match:
        macaddress: 00:25:90:a3:ff:c0
      addresses:
      - 192.168.0.12/24
      gateway4: 192.168.0.1
      dhcp4: false
      dhcp6: false
      link-local: []
      nameservers:
        addresses:
        - 192.168.0.2
      mtu: 9000
```
